name: Build
on: 
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ls -al app/build/outputs/apk/debug/*.apk
      - name: Save debug-apk
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: debug-apk
          # A file, directory or wildcard pattern that describes what to upload
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
      - name: add artifact links to pull request and related issues step
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            prefix: Here are the artifacts 
            suffix: Have a nice day.
            format: name
            addTo: pullandissues
