name: Build
on: 
  pull_request:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ls -al app/build/outputs/apk/debug/app-debug.apk
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: debug-apk
          # A file, directory or wildcard pattern that describes what to upload
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          # Artifact name
          name: debug-apk
          # Destination path
          path: app/build/outputs/apk/debug/app-debug.apk
